meta_product_name: "WorkingLatte"
meta_title: "WorkingLatte - Working remote made easier."
meta_description: "Working remote made easier, while having the best coffee wherever you are!"
meta_image: "metaimg.jfif"
